/**
 * Keyword → MCP server mapping for tool filtering.
 * If ANY keyword in an order matches, that server's tools are included.
 */
export const SERVER_KEYWORDS: Record<string, string[]> = {
    'mcp-hue': [
        'lumière',
        'lampe',
        'allume',
        'éteins',
        'éclairage',
        'luminosité',
        'couleur',
        'light',
        'lamp',
        'chambre',
        'salon',
        'cuisine',
        'bureau',
        'salle',
        'ambiance',
        'bright',
        'dim',
    ],
    'mcp-nuki': ['porte', 'verrou', 'clé', 'ferme', 'ouvre', 'lock', 'door'],
    'mcp-spotify': [
        'musique',
        'spotify',
        'joue',
        'chanson',
        'playlist',
        'album',
        'artiste',
        'écoute',
        'volume',
        'pause',
        'music',
        'son',
        'radio',
        'morceau',
        'track',
        'shuffle',
        'repeat',
    ],
    'mcp-linear': [
        'linear',
        'ticket',
        'issue',
        'tâche',
        'projet',
        'koya',
        'bug',
    ],
    'mcp-samsung': [
        'tv',
        'télé',
        'télévision',
        'samsung',
        'écran',
        'hdmi',
        'volume',
    ],
    'mcp-chromecast': [
        'chromecast',
        'cast',
        'netflix',
        'crunchyroll',
        'youtube',
        'disney',
        'prime',
        'amazon',
        'cinéma',
        'film',
        'série',
        'diffuse',
        'stream',
        'vidéo',
        'anime',
    ],
    'mcp-calendar': [
        'calendrier',
        'agenda',
        'réunion',
        'rendez-vous',
        'événement',
        'planning',
        'semaine',
        'demain',
        'lundi',
        'mardi',
        'mercredi',
        'jeudi',
        'vendredi',
        'samedi',
        'dimanche',
        'aujourd',
        'mois',
    ],
    'mcp-weather': [
        'météo',
        'temps',
        'température',
        'pluie',
        'soleil',
        'vent',
        'chaud',
        'froid',
        'nuage',
        'weather',
        'demain',
        'prévision',
        'semaine prochaine',
        'après-demain',
        'forecast',
    ],
    'mcp-obsidian': [
        'note',
        'obsidian',
        'fichier',
        'document',
        'écris',
        'journal',
        'vault',
    ],
    'mcp-gmail': [
        'email',
        'mail',
        'gmail',
        'message',
        'inbox',
        'boîte',
        'envoie',
        'reçu',
        'expéditeur',
        'destinataire',
        'objet',
        'pièce jointe',
        'brouillon',
        'archive',
        'corbeille',
        'non lu',
        'marque',
    ],
};
